# Generated by Django 2.2.5 on 2019-09-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(upload_to='media/receitas'),
        ),
    ]
