# Generated by Django 2.2.5 on 2019-10-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190929_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.CharField(default='', max_length=80, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
